### ISSUE TITLE
G-Suite SAML Instructions

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-console-guide#29]

**Comment by mdeggies** [comment]
Draft: 

Log in to admin.google.com. Click on the ‘Apps’ box and then click on ‘SAML apps’. Click the + button to add a new SAML Application. Scroll to the bottom of the modal and click on ‘Setup my Own Custom App’.

Save the SSO URL and the Entity ID provided. Click *download* to download the Certificate. This will download a .pem file with a name starting with GoogleIDPCertificate.

Open a new browser tab and log in to the Stormpath Admin Console. Create a new SAML Directory. For ‘SAML SSO Login Url’ and ‘SAML SSO Logout Url’, enter the SSO URL from your Google SAML Application. For ‘SAML X.509 Signing Cert’, copy the contents of the GoogleIDPCertificate.pem file (from the previous step) into the text box. For ‘SAML Request Signature Algorithm’, make sure that ’RSA-SHA256’ is selected. Click ‘Create Directory’. 

You’ll now be on a page with the details of your Directory. Click on the ‘Identity Provider’ tab. Copy the ‘Entity ID’ and the ‘Assertion Consumer Service URL’. 

Back to your other browser tab, you should be on step 2: ‘Google IdP Information’. Click ‘Next’ and enter in your Application Name, and optionally enter in a Description and upload a logo. Then click ‘Next’ to continue. You should be on step 4: ‘Service Provider Details’. 

For ‘ACS URL’, enter in the ‘Assertion Consumer Service URL’ saved in the previous step. For ‘Entity ID’, enter in the ‘Entity ID’ saved in the previous step. Make sure that the ‘Name ID’ is ‘Basic Information’ and ‘Primary Email’, and that the ‘Name ID Format’ is of type ‘Email’. Click ‘Next’.

You can optionally add attribute mappings here, but that is not required. Click ‘Finish’ to create your Application. 

Click on the SAML Application you just created from the list. Turn the Application ‘ON’. You can either turn it on for everyone, or for users in your Organization only. 

Make sure that you’ve mapped your Stormpath SAML Directory to one of your Applications as an Account Store.

Now test out your SP-initiated connection! 

For the IDP Initiated flow, please navigate back to the Stormpath Admin Console and click on your SAML Directory. Click on the ‘Identity Provider’ tab and click on ‘Generate Default Relay State’. 

NOTE: When you generate a relay state, you'll need to select an Application, an API key ID, and input a callback URL. The Callback URL should be the URL that the authentication result will be sent to. This URL will need to handle the authentication result (the JWT). If you’re using one of our integrations, this will be ‘https://your-site.com/idSiteResult'. This URL will also need to be added to your Stormpath Application’s Authorized Callback URI’s list. For more information, please refer to our ID Site documentation. 

Once you’ve generated the default relay state, please save it. Navigate back to your Google SAML Application and click on ‘Service Provider Details’. Under ’Start URL’, enter the default relay state.

That’s it! You can test the SP-initiated flow by starting your web app (using the same API key ID and secret that was used to generate the default relay state). Next, navigate to your login page and click on the 'G-Suite SAML' button. Authenticate with your G-Suite credentials, and then see that you're redirected back to your web app.

To test the IDP-initiated flow, log back into the Google Admin Console at https://admin.google.com. Navigate to your configured SAML App, and click on the ‘Launch this app’ button. You'll be automatically redirected back to your web app with an authentication result, and the callback URL will make sure you're authenticated.

**Comment by mdeggies** [comment]
https://github.com/stormpath/stormpath-console-guide/pull/44
